### 메뉴 카테고리 리스트 조회

GET http://{{apiUrl}}/restaurant/1/menu/categories
Accept: application/json

### 메뉴 카테고리 생성(추가)
POST http://{{apiUrl}}/restaurant/1/menu/category?userSeq=1
Content-Type: application/json

{
    "name": "1인분메뉴",
    "exposed": true,
    "viewOrder": 1
}

